s=open('fill2.py').read()
GOOD3="""ACE ACT ADD AGE AGO AID AIM AIR ALE ALL AND ANT ANY APE APT ARC ARE ARK ARM ART ASH ASK
ATE AWE AXE BAD BAG BAN BAR BAT BAY BED BEE BEG BET BIB BID BIG BIN BIT BOA BOB BOG BOO BOW BOX BOY BRA BUD BUG BUN BUS BUT BUY BYE CAB CAD CAN CAP CAR CAT COB COD COG CON COO COP COT COW COY CRY CUB CUE CUP CUR CUT DAB DAD DAM DAY DEN DEW DID DIE DIG DIM DIN DIP DOE DOG DON DOT DRY DUB DUE DUG DUO DYE EAR EAT EBB EEL EGG EGO ELF ELK ELM EMU END EON ERA EVE EWE EYE FAD FAN FAR FAT FAX FED FEE FEW FIB FIG FIN FIR FIT FIX FLU FLY FOE FOG FOR FOX FRY FUN FUR GAP GAS GEL GEM GET GIG GIN GNU GOD GOT GUM GUN GUT GUY GYM HAD HAG HAM HAS HAT HAY HEM HEN HER HEW HEY HID HIM HIP HIS HIT HOE HOG HOP HOT HOW HUB HUE HUG HUM HUT ICE ICY ILK ILL IMP INK INN ION IRE IRK IVY JAB JAM JAR JAW JAY JET JIG JOB JOG JOT JOY JUG KEG KEY KID KIN KIT LAB LAD LAG LAP LAW LAY LED LEG LET LID LIE LIP LIT LOB LOG LOT LOW MAD MAN MAP MAR MAT MAY MEN MET MIX MOB MOD MOM MOP MUD MUG MUM NAB NAG NAP NET NEW NIL NIP NOD NOR NOT NOW NUN NUT OAK OAR OAT ODD ODE OFF OFT OIL OLD ONE OPT ORB ORE OUR OUT OWE OWL OWN PAD PAL PAN PAR PAT PAW PAY PEA PEG PEN PEP PER PET PEW PIE PIG PIN PIT PLY POD POP POT PRO PRY PUB PUG PUN PUP PUT RAG RAM RAN RAP RAT RAW RAY RED RIB RID RIG RIM RIP ROB ROD ROE ROT ROW RUB RUG RUM RUN RUT RYE SAD SAG SAP SAT SAW SAY SEA SEE SET SEW SHE SHY SIN SIP SIR SIT SIX SKI SKY SLY SOB SOD SON SOW SOY SPA SPY STY SUB SUE SUM SUN SUP TAB TAD TAG TAN TAP TAR TAX TEA TEN THE THY TIC TIE TIN TIP TOE TON TOO TOP TOT TOW TOY TRY TUB TUG TUX TWO URN USE VAN VAT VET VIA VIE VOW WAD WAG WAR WAS WAX WAY WEB WED WEE WET WHO WHY WIG WIN WIT WOE WOK WON WOO WOW WRY YAK YAM YAP YAW YEA YEN YES YET YEW YOU ZAP ZIP ZOO""".split()
GOOD3=set(GOOD3)
s=s.replace(
"pool=[w for w in common if w in DICT and w not in STOP and rank[w]<30000]",
"GOOD3="+repr(GOOD3)+"\n"
"pool=[w for w in common if w in DICT and w not in STOP and rank[w]<26000 and (len(w)!=3 or w in GOOD3)]\n"
"pool+=[w for w in GOOD3 if w not in set(pool)]\n"
"rank.update({w:rank.get(w,15000) for w in GOOD3})")
open('fill2.py','w').write(s)
print("ok")
